name: build Docker image, run E2E BE tests, run E2E FE tests

on:
  push:
    branches:
      - "**"
    tags:
      - '**'
  pull_request:
    paths-ignore:
      - 'docs/**'
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write

jobs:
  build-docker-image:
    uses: netcracker/qubership-apihub-ci/.github/workflows/docker-ci.yml@main
    with:
      name: qubership-apihub-agents-backend
      file: Dockerfile
      context: ""
      platforms: linux/amd64,linux/arm64
      labels: |
        maintainer=qubership

  calculate-backend-tag:
    if: github.event_name == 'pull_request'
    needs: build-docker-image
    uses: netcracker/qubership-apihub-ci/.github/workflows/calculate-effective-tag.yaml@main
    with:
      branch-name: ${{ github.head_ref }}
      repo-name: qubership-apihub-backend

  calculate-ui-tag:
    if: github.event_name == 'pull_request'
    needs: build-docker-image
    uses: netcracker/qubership-apihub-ci/.github/workflows/calculate-effective-tag.yaml@main
    with:
      branch-name: ${{ github.head_ref }}
      repo-name: qubership-apihub-ui

  calculate-build-task-consumer-tag:
    if: github.event_name == 'pull_request'
    needs: build-docker-image
    uses: netcracker/qubership-apihub-ci/.github/workflows/calculate-effective-tag.yaml@main
    with:
      branch-name: ${{ github.head_ref }}
      repo-name: qubership-apihub-build-task-consumer

  calculate-api-linter-service-tag:
    if: github.event_name == 'pull_request'
    needs: build-docker-image
    uses: netcracker/qubership-apihub-ci/.github/workflows/calculate-effective-tag.yaml@main
    with:
      branch-name: ${{ github.head_ref }}
      repo-name: qubership-api-linter-service

  run-e2e-tests:
    uses: netcracker/qubership-apihub-ci/.github/workflows/run-e2e-tests-kind.yaml@main
    needs:
      - build-docker-image
      - calculate-backend-tag
      - calculate-ui-tag
      - calculate-build-task-consumer-tag
      - calculate-api-linter-service-tag
    if: github.event_name == 'pull_request'
    with:
      postman-collections-list: './e2e/1_1_Smoke_Portal.postman_collection.json,./e2e/1_2_Smoke_Agent.postman_collection.json'
      playwright-tests-run: false
      apihub-backend-image-tag: ${{ needs.calculate-backend-tag.outputs.tag }}
      apihub-ui-image-tag: ${{ needs.calculate-ui-tag.outputs.tag }}
      apihub-build-task-consumer-image-tag: ${{ needs.calculate-build-task-consumer-tag.outputs.tag }}
      apihub-api-linter-service-image-tag: ${{ needs.calculate-api-linter-service-tag.outputs.tag }}
      apihub-agents-backend-image-tag: ${{ needs.build-docker-image.outputs.image_tag }}
      apihub-agent-run: true
    secrets:
      APIHUB_ACCESS_TOKEN: ${{ secrets.APIHUB_ACCESS_TOKEN }}
      APIHUB_ADMIN_EMAIL: ${{ secrets.APIHUB_ADMIN_EMAIL }}
      APIHUB_ADMIN_PASSWORD: ${{ secrets.APIHUB_ADMIN_PASSWORD }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
