import { DefaultValueMapping } from "../unifies/defaults"
import {
  ASYNCAPI_PROPERTY_BINDINGS,
  ASYNCAPI_PROPERTY_CHANNELS,
  ASYNCAPI_PROPERTY_COMPONENTS,
  ASYNCAPI_PROPERTY_CONTACT,
  ASYNCAPI_PROPERTY_CORRELATION_IDS,
  ASYNCAPI_PROPERTY_CHANNEL_BINDINGS,
  ASYNCAPI_PROPERTY_ENUM,
  ASYNCAPI_PROPERTY_EXAMPLES,
  ASYNCAPI_PROPERTY_EXTERNAL_DOCS,
  ASYNCAPI_PROPERTY_FLOWS,
  ASYNCAPI_PROPERTY_SCOPES,
  ASYNCAPI_PROPERTY_HEADERS,
  ASYNCAPI_PROPERTY_SECURITY,
  ASYNCAPI_PROPERTY_SERVERS,
  ASYNCAPI_PROPERTY_TAGS,
  ASYNCAPI_PROPERTY_TRAITS,
  ASYNCAPI_PROPERTY_VARIABLES,
  ASYNCAPI_PROPERTY_MESSAGE_TRAITS,
  ASYNCAPI_PROPERTY_REPLY,
  ASYNCAPI_PROPERTY_REPLY_ADDRESSES,
  ASYNCAPI_PROPERTY_REPLIES,
  ASYNCAPI_PROPERTY_SCHEMAS,
  ASYNCAPI_PROPERTY_MESSAGE_BINDINGS,
  ASYNCAPI_PROPERTY_OPERATIONS,
  ASYNCAPI_PROPERTY_MESSAGES,
  ASYNCAPI_PROPERTY_SECURITY_SCHEMES,
  ASYNCAPI_PROPERTY_PARAMETERS,
  ASYNCAPI_PROPERTY_OPERATION_TRAITS,
  ASYNCAPI_PROPERTY_SERVER_BINDINGS,
  ASYNCAPI_PROPERTY_OPERATION_BINDINGS,
  ASYNCAPI_PROPERTY_LICENSE,
  ASYNCAPI_PROPERTY_INFO,
  ASYNCAPI_PROPERTY_SERVER_VARIABLES,
  ASYNCAPI_PROPERTY_CONTENT_TYPE
} from "./asyncapi.const"
import { EMPTY_MARKER, TO_EMPTY_ARRAY_MAPPING, TO_EMPTY_OBJECT_MAPPING, ReplaceMapping } from "../unifies/replaces"
import { UnifyFunction, DefaultMetaRecord, DEFAULT_TYPE_FLAG_SYNTHETIC, DEFAULT_TYPE_FLAG_PURE } from '../types'
import { isObject, isArray } from '@netcracker/qubership-apihub-json-crawl'
import { setJsoProperty } from '../utils'
import { resolveOriginsMetaRecord } from '../origins'

export const ASYNCAPI_TAG_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
}

export const ASYNCAPI_TAG_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_SECURITY_SCHEME_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_FLOWS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SCOPES]: EMPTY_MARKER,
}

export const ASYNCAPI_SECURITY_SCHEME_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_FLOWS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SCOPES]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_SERVER_VARIABLE_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_ENUM]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXAMPLES]: EMPTY_MARKER,
}

export const ASYNCAPI_SERVER_VARIABLE_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_ENUM]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXAMPLES]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_SERVER_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_VARIABLES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SECURITY]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_TAGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_BINDINGS]: EMPTY_MARKER,
}

export const ASYNCAPI_SERVER_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_VARIABLES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SECURITY]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_TAGS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_MESSAGE_EXAMPLE_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_HEADERS]: EMPTY_MARKER,
}

export const ASYNCAPI_MESSAGE_EXAMPLE_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_HEADERS]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_MESSAGE_TRAIT_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_TAGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_BINDINGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXAMPLES]: EMPTY_MARKER,
}

export const ASYNCAPI_MESSAGE_TRAIT_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_TAGS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_EXAMPLES]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_MESSAGE_DEFAULTS: DefaultValueMapping = {
  ...ASYNCAPI_MESSAGE_TRAIT_DEFAULTS,
  [ASYNCAPI_PROPERTY_TRAITS]: EMPTY_MARKER,
}

export const ASYNCAPI_MESSAGE_REPLACES: Record<string, ReplaceMapping> = {
  ...ASYNCAPI_MESSAGE_TRAIT_REPLACES,
  [ASYNCAPI_PROPERTY_TRAITS]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_PARAMETER_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_ENUM]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXAMPLES]: EMPTY_MARKER,
}

export const ASYNCAPI_PARAMETER_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_ENUM]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXAMPLES]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_CHANNEL_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_MESSAGES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SERVERS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_PARAMETERS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_TAGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_BINDINGS]: EMPTY_MARKER,
}

export const ASYNCAPI_CHANNEL_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_MESSAGES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SERVERS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_PARAMETERS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_TAGS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_OPERATION_REPLY_DEFAULTS: DefaultValueMapping = {
  //TODO: decide if we need default for channel property
  [ASYNCAPI_PROPERTY_MESSAGES]: EMPTY_MARKER,
}

export const ASYNCAPI_OPERATION_REPLY_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_MESSAGES]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_OPERATION_TRAIT_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_SECURITY]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_TAGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_BINDINGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_REPLY]: EMPTY_MARKER,
}

export const ASYNCAPI_OPERATION_TRAIT_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_SECURITY]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_TAGS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_REPLY]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_OPERATION_DEFAULTS: DefaultValueMapping = {
  ...ASYNCAPI_OPERATION_TRAIT_DEFAULTS,
  //TODO: decide if we need default for channel property
  [ASYNCAPI_PROPERTY_TRAITS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_MESSAGES]: EMPTY_MARKER,
}

export const ASYNCAPI_OPERATION_REPLACES: Record<string, ReplaceMapping> = {
  ...ASYNCAPI_OPERATION_TRAIT_REPLACES,
  [ASYNCAPI_PROPERTY_TRAITS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_MESSAGES]: TO_EMPTY_ARRAY_MAPPING,
}

export const ASYNCAPI_COMPONENTS_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_SCHEMAS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SERVERS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_CHANNELS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_OPERATIONS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_MESSAGES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SECURITY_SCHEMES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SERVER_VARIABLES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_PARAMETERS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_CORRELATION_IDS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_REPLIES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_REPLY_ADDRESSES]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_TAGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_OPERATION_TRAITS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_MESSAGE_TRAITS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SERVER_BINDINGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_CHANNEL_BINDINGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_OPERATION_BINDINGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_MESSAGE_BINDINGS]: EMPTY_MARKER,
}

export const ASYNCAPI_COMPONENTS_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_SCHEMAS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SERVERS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_CHANNELS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_OPERATIONS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_MESSAGES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SECURITY_SCHEMES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SERVER_VARIABLES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_PARAMETERS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_CORRELATION_IDS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_REPLIES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_REPLY_ADDRESSES]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_TAGS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_OPERATION_TRAITS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_MESSAGE_TRAITS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SERVER_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_CHANNEL_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_OPERATION_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_MESSAGE_BINDINGS]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_INFO_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_CONTACT]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_LICENSE]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_TAGS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: EMPTY_MARKER,
}

export const ASYNCAPI_INFO_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_CONTACT]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_LICENSE]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_TAGS]: TO_EMPTY_ARRAY_MAPPING,
  [ASYNCAPI_PROPERTY_EXTERNAL_DOCS]: TO_EMPTY_OBJECT_MAPPING,
}

export const ASYNCAPI_ROOT_DEFAULTS: DefaultValueMapping = {
  [ASYNCAPI_PROPERTY_INFO]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_SERVERS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_CHANNELS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_OPERATIONS]: EMPTY_MARKER,
  [ASYNCAPI_PROPERTY_COMPONENTS]: EMPTY_MARKER,
}

export const ASYNCAPI_ROOT_REPLACES: Record<string, ReplaceMapping> = {
  [ASYNCAPI_PROPERTY_INFO]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_SERVERS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_CHANNELS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_OPERATIONS]: TO_EMPTY_OBJECT_MAPPING,
  [ASYNCAPI_PROPERTY_COMPONENTS]: TO_EMPTY_OBJECT_MAPPING,
}

export const contentTypeDefault: UnifyFunction = {
  forward: (jso, ctx) => {
    const { options } = ctx

    // Only applies to objects
    if (!isObject(jso) || isArray(jso)) {
      return jso
    }

    // Get defaultContentType from root document
    const rootDoc = options.source
    if (!isObject(rootDoc) || isArray(rootDoc)) {
      return jso
    }

    const defaultContentType = rootDoc.defaultContentType
    if (typeof defaultContentType !== 'string') {
      return jso
    }

    const CONTENT_TYPE_KEY = ASYNCAPI_PROPERTY_CONTENT_TYPE
    let shallowJso = jso
    let needsUpdate = false

    // Handle synthetic default (property missing)
    if (!(CONTENT_TYPE_KEY in jso)) {
      shallowJso = { ...jso, [CONTENT_TYPE_KEY]: defaultContentType }
      needsUpdate = true

      // Mark as synthetic
      if (options.defaultsFlag) {
        const defaultsMeta = { ...shallowJso[options.defaultsFlag] ?? {} }
        defaultsMeta[CONTENT_TYPE_KEY] = DEFAULT_TYPE_FLAG_SYNTHETIC
        shallowJso[options.defaultsFlag] = defaultsMeta
      }

      // Set custom origin pointing to root's defaultContentType
      if (options.originsFlag) {
        const originsRecord = resolveOriginsMetaRecord(shallowJso, options.originsFlag) ?? {}

        // Get the origin from the root document's defaultContentType property
        const rootOriginsRecord = resolveOriginsMetaRecord(rootDoc, options.originsFlag)
        if (rootOriginsRecord && 'defaultContentType' in rootOriginsRecord) {
          originsRecord[CONTENT_TYPE_KEY] = rootOriginsRecord['defaultContentType']
        }

        setJsoProperty(shallowJso, options.originsFlag, originsRecord)
      }
    }
    // Handle pure default (property exists with default value)
    else if (jso[CONTENT_TYPE_KEY] === defaultContentType) {
      if (options.defaultsFlag) {
        shallowJso = { ...jso }
        needsUpdate = true
        const defaultsMeta = { ...shallowJso[options.defaultsFlag] ?? {} }
        defaultsMeta[CONTENT_TYPE_KEY] = DEFAULT_TYPE_FLAG_PURE
        shallowJso[options.defaultsFlag] = defaultsMeta
      }
    }

    return needsUpdate ? shallowJso : jso
  },

  backward: (jso, ctx) => {
    const { options } = ctx
    if (!isObject(jso) || isArray(jso)) {
      return
    }

    // Get defaultContentType from root document
    const rootDoc = options.source
    if (!isObject(rootDoc) || isArray(rootDoc)) {
      return
    }

    const defaultContentType = rootDoc.defaultContentType
    if (typeof defaultContentType !== 'string') {
      return
    }

    const CONTENT_TYPE_KEY = ASYNCAPI_PROPERTY_CONTENT_TYPE

    // Only remove if it matches the default AND was synthetic (not pure)
    if (jso[CONTENT_TYPE_KEY] === defaultContentType) {
      // Check if it's marked as synthetic (not pure)
      let shouldRemove = true

      if (options.defaultsFlag && options.defaultsFlag in jso) {
        const defaultsMeta = jso[options.defaultsFlag] as DefaultMetaRecord
        delete jso[options.defaultsFlag]
        if (defaultsMeta[CONTENT_TYPE_KEY] === DEFAULT_TYPE_FLAG_PURE) {
          shouldRemove = false  // Keep pure defaults (explicitly set in original)
        }
      }

      if (shouldRemove) {
        delete jso[CONTENT_TYPE_KEY]

        // Clean up origins
        if (options.originsFlag) {
          const originsRecord = resolveOriginsMetaRecord(jso, options.originsFlag)
          if (originsRecord && CONTENT_TYPE_KEY in originsRecord) {
            delete originsRecord[CONTENT_TYPE_KEY]
          }
        }
      }
    }
  }
}
