type Mutation {
    createPackage(input: PackageInput): Package
}

input PackageInput {
    id: Float
    name: String
    parentPackage: PackageInput  # Circular reference
}

type Package {
    id: Float #
    name: String
    parentPackage: Package # Circular reference
}