import { DiffTemplateParamsCalculator } from '../types'
import {
  DIFF_ACTION_TO_ACTION_MAP,
  DIFF_ACTION_TO_PREPOSITION_MAP,
  GREP_TEMPLATE_PARAM_ENCODING_NAME,
  GREP_TEMPLATE_PARAM_EXAMPLE_NAME,
  GREP_TEMPLATE_PARAM_HEADER_NAME,
  GREP_TEMPLATE_PARAM_MEDIA_TYPE,
  GREP_TEMPLATE_PARAM_PARAMETER_NAME,
  GREP_TEMPLATE_PARAM_RESPONSE_NAME
} from '../core'
import { checkPrimitiveType, resolveAllDeclarationPath } from '../utils'
import {
  grepValue,
  matchPaths,
  OPEN_API_HTTP_METHODS,
  OPEN_API_PROPERTY_COMPONENTS,
  OPEN_API_PROPERTY_CONTENT,
  OPEN_API_PROPERTY_ENCODING,
  OPEN_API_PROPERTY_EXAMPLES,
  OPEN_API_PROPERTY_HEADERS,
  OPEN_API_PROPERTY_PARAMETERS,
  OPEN_API_PROPERTY_PATHS,
  OPEN_API_PROPERTY_REQUEST_BODIES,
  OPEN_API_PROPERTY_REQUEST_BODY,
  OPEN_API_PROPERTY_RESPONSES,
  PREDICATE_ANY_VALUE,
  PREDICATE_UNCLOSED_END,
} from '@netcracker/qubership-apihub-api-unifier'
import {
  calculateChangedProperty,
  calculateComponentsPath,
  calculateEncodingPlaceInRequest,
  calculateEncodingPlaceInResponse,
  calculateHeaderPlace,
  calculateParameterPlace,
  calculateRequestPlace,
  calculateResponsePlace
} from './openapi3.description'

export const examplesParamsCalculator: DiffTemplateParamsCalculator = (diff, ctx) => {
  const result = {
    action: DIFF_ACTION_TO_ACTION_MAP[diff.action],
    preposition: DIFF_ACTION_TO_PREPOSITION_MAP[diff.action]
  }

  const declarationPaths = resolveAllDeclarationPath(diff)

  let matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_EXAMPLES)
  if (matchResult) {
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    return {
      ...result,
      exampleName
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES)
  if (matchResult) {
    const propertyName = calculateChangedProperty(matchResult, true)
    const examplePath = calculateComponentsPath(matchResult)
    return {
      ...result,
      propertyName,
      examplePath
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_PARAMETERS)
  if (matchResult) {
    const place = calculateParameterPlace(matchResult, diff, ctx)
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_REQUEST)
  if (matchResult) {
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    const place = calculateRequestPlace(matchResult)
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_RESPONSE)
  if (matchResult) {
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    const place = calculateResponsePlace(matchResult)
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_HEADER)
  if (matchResult) {
    const place = calculateHeaderPlace(matchResult)
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_HEADER_IN_RESPONSE)
  if (matchResult) {
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    const place = calculateHeaderPlace(matchResult)
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_ENCODING_IN_HEADER_IN_RESPONSE)
  if (matchResult) {
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    const place = calculateEncodingPlaceInResponse(matchResult)
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  matchResult = matchPaths(declarationPaths, PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_ENCODING_IN_HEADER_IN_REQUEST)
  if (matchResult) {
    const propertyName = calculateChangedProperty(matchResult, true)
    const exampleName = checkPrimitiveType(matchResult.grepValues[GREP_TEMPLATE_PARAM_EXAMPLE_NAME])
    const place = calculateEncodingPlaceInRequest(matchResult)
    return {
      ...result,
      propertyName,
      exampleName,
      place
    }
  }

  return result
}
const PREDICATES_PATHS_FOR_CHANGED_EXAMPLES = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],

  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_PARAMETERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_PARAMETERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_PARAMETERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_PARAMETERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)]),

  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_REQUEST_BODIES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_CONTENT, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_REQUEST_BODY, OPEN_API_PROPERTY_CONTENT, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)]),

  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_RESPONSES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_CONTENT, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_RESPONSES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_CONTENT, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)]),

  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_HEADERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_RESPONSES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_HEADERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_RESPONSES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_HEADERS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)]),

]
const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_EXAMPLES, PREDICATE_ANY_VALUE, PREDICATE_UNCLOSED_END],
]
const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_PARAMETERS = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_PARAMETERS, grepValue(GREP_TEMPLATE_PARAM_PARAMETER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END],
  [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_PARAMETERS, grepValue(GREP_TEMPLATE_PARAM_PARAMETER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_PARAMETERS, grepValue(GREP_TEMPLATE_PARAM_PARAMETER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END]),
]
const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_REQUEST = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_REQUEST_BODIES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_REQUEST_BODY, OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END]),
]
const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_RESPONSE = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_RESPONSES, grepValue(GREP_TEMPLATE_PARAM_RESPONSE_NAME), OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_RESPONSES, grepValue(GREP_TEMPLATE_PARAM_RESPONSE_NAME), OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)])
]
const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_HEADER = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
]
const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_HEADER_IN_RESPONSE = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_RESPONSES, grepValue(GREP_TEMPLATE_PARAM_RESPONSE_NAME), OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_RESPONSES, grepValue(GREP_TEMPLATE_PARAM_RESPONSE_NAME), OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME)]),
]
export const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_ENCODING_IN_HEADER_IN_RESPONSE = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_RESPONSES, grepValue(GREP_TEMPLATE_PARAM_RESPONSE_NAME), OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_ENCODING, grepValue(GREP_TEMPLATE_PARAM_ENCODING_NAME), OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_RESPONSES, grepValue(GREP_TEMPLATE_PARAM_RESPONSE_NAME), OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_ENCODING, grepValue(GREP_TEMPLATE_PARAM_ENCODING_NAME), OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END])
]
export const PREDICATES_PATHS_FOR_CHANGED_FIELD_IN_EXAMPLES_IN_ENCODING_IN_HEADER_IN_REQUEST = [
  [OPEN_API_PROPERTY_COMPONENTS, OPEN_API_PROPERTY_REQUEST_BODIES, PREDICATE_ANY_VALUE, OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_ENCODING, grepValue(GREP_TEMPLATE_PARAM_ENCODING_NAME), OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END],
  ...OPEN_API_HTTP_METHODS.map(httpMethod => [OPEN_API_PROPERTY_PATHS, PREDICATE_ANY_VALUE, httpMethod, OPEN_API_PROPERTY_REQUEST_BODY, OPEN_API_PROPERTY_CONTENT, grepValue(GREP_TEMPLATE_PARAM_MEDIA_TYPE), OPEN_API_PROPERTY_ENCODING, grepValue(GREP_TEMPLATE_PARAM_ENCODING_NAME), OPEN_API_PROPERTY_HEADERS, grepValue(GREP_TEMPLATE_PARAM_HEADER_NAME), OPEN_API_PROPERTY_EXAMPLES, grepValue(GREP_TEMPLATE_PARAM_EXAMPLE_NAME), PREDICATE_UNCLOSED_END]),
]
