openapi: 3.0.0
info:
  title: test
  version: 0.1.0
paths:
  /pets/{param1}:
    post:
      parameters:
        - name: param1
          in: path
          required: true          
          schema:
            type: string
          style: simple
      responses:
        '200':
          description: OK