type Query {
    salesOrder: SalesOrder
}

type SalesOrder {
    id: String
    price: Price
}

type Price {
    oneTimeDiscount: MonetaryValue
    oneTimeTotalWithTax: MonetaryValue
    oneTimeTotalWithTaxDiscounted: MonetaryValue
}

type MonetaryValue {
    value: String # Changed from Float to String
    currency: String
}