package service

import (
	"context"
	"encoding/json"
	"strconv"
	"time"

	"github.com/Netcracker/qubership-api-linter-service/client"
	"github.com/Netcracker/qubership-api-linter-service/view"
	log "github.com/sirupsen/logrus"

	"github.com/AsaiYusuke/jsonpath/v2"
)

type AiOasExecutor interface {
	LintOperationForDoc(ctx context.Context, operationData string, rulesetData view.AiRuleset) ([]view.ValidationIssue, int64, error)
	DeduplicateIssues(ctx context.Context, issues []view.ValidationIssue) ([]view.ValidationIssue, int64, error)
	GetLinterVersion() string
}

func NewAiOasExecutor(systemInfoService SystemInfoService) (AiOasExecutor, error) {
	var llmCl client.LLMClient
	var err error
	if systemInfoService.IsAiOasLinterEnabled() {
		llmCl, err = client.NewOpenaiClient(
			systemInfoService.GetOpenAIAPIKey(),
			systemInfoService.GetOpenAIModel(),
			systemInfoService.GetOpenAIAPIProxy(),
			systemInfoService.GetOpenAIRateLimitRPS(),
			systemInfoService.GetOpenAIRateLimitBurst())
		if err != nil {
			return nil, err
		}
	} else {
		llmCl = client.NewStubLlmClient()
	}

	return &aiOasExecutor{
		llmClient: llmCl,
	}, nil
}

type aiOasExecutor struct {
	llmClient client.LLMClient
}

func (s *aiOasExecutor) LintOperationForDoc(ctx context.Context, operationData string, rulesetData view.AiRuleset) ([]view.ValidationIssue, int64, error) {
	start := time.Now()

	issues, err := s.llmClient.LintOasDocument(ctx, operationData, rulesetData.Prompt)
	if err != nil {
		return nil, 0, err
	}

	var src any
	err = json.Unmarshal([]byte(operationData), &src)
	if err != nil {
		return nil, 0, err
	}

	var res []view.ValidationIssue
	for _, iss := range issues {
		jsonPath := "$"
		parentJsonPath := ""

		for i, p := range iss.Path {
			_, errC := strconv.Atoi(p)
			if errC != nil {
				jsonPath += "['" + p + "']"
			} else {
				jsonPath += "[" + p + "]"
			}
			if i == (len(iss.Path) - 2) {
				parentJsonPath = jsonPath
			}
		}

		parsed, err := jsonpath.Parse(jsonPath)
		if err != nil {
			log.Errorf("Failed to parse jsonpath from Ai linter - '%s': %s", jsonPath, err)
			continue
		}
		_, err = parsed(src)
		if err != nil {
			// try parent json path
			parsedParent, errP := jsonpath.Parse(parentJsonPath)
			if errP != nil {
				log.Warnf("Failed to parse parent jsonpath from Ai linter - '%s': %s", parentJsonPath, errP)
				continue
			}
			_, errP = parsedParent(src)
			if errP != nil {
				log.Warnf("incorrect jsonpath generated by Ai linter - '%s': %s. Parent is not working too - '%s' : %s", jsonPath, err, parentJsonPath, errP)
				continue
			}
			// TODO: or add with empty path?
		}

		res = append(res, view.ValidationIssue{
			Path:     iss.Path,
			Code:     iss.Code,
			Severity: iss.Severity,
			Message:  iss.Message,
		})
	}
	calculationTime := time.Since(start)

	return res, calculationTime.Milliseconds(), nil
}

func (s *aiOasExecutor) DeduplicateIssues(ctx context.Context, issues []view.ValidationIssue) ([]view.ValidationIssue, int64, error) {
	start := time.Now()

	dIssues, err := s.llmClient.DeduplicateIssues(ctx, issues)
	if err != nil {
		return nil, 0, err
	}

	var res []view.ValidationIssue
	for _, iss := range dIssues {
		res = append(res, view.ValidationIssue{
			Path:     iss.Path,
			Code:     iss.Code,
			Severity: iss.Severity,
			Message:  iss.Message,
		})
	}
	calculationTime := time.Since(start)
	return res, calculationTime.Milliseconds(), nil
}

func (s *aiOasExecutor) GetLinterVersion() string {
	return "1.0"
}
