CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE public.projects (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  name character varying(1000) NOT NULL
    CONSTRAINT projects_name_length CHECK (char_length(name) >= 1),
  description text,
  CONSTRAINT projects_name_key UNIQUE (name)
);

COMMENT ON COLUMN public.projects.description IS 'Stub long comment for ddlapi viewer sample fixtures and Storybook testing only. This placeholder text is intentionally verbose so the API doc viewer can render multiline column and index descriptions at realistic lengths without using production documentation. Segment A: lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Segment B: ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Segment C: duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore end stub.';

COMMENT ON INDEX projects_name_key IS 'Stub index comment for ddlapi sample fixture tests.';
