name: Storybook CD Workflow

on:
  push:
    branches:
      - '**'
  delete: {}

jobs:
  call-storybook-cd-workflow:
    uses: netcracker/qubership-apihub-ci/.github/workflows/storybook-cd.yaml@main
