import { DIFF_META_KEY, DIFFS_AGGREGATED_META_KEY } from '@netcracker/qubership-apihub-api-diff'
import { FIRST_REFERENCE_KEY_PROPERTY, HASH_FLAG, ORIGINS_SYMBOL, SYNTHETIC_TITLE_FLAG } from '@netcracker/qubership-apihub-api-processor'

export const INTERNAL_DOCUMENT_STRING_SYMBOL_MAPPING = new Map([
  ['HASH_FLAG', HASH_FLAG],
  ['ORIGINS_SYMBOL', ORIGINS_SYMBOL],
  ['SYNTHETIC_TITLE_FLAG', SYNTHETIC_TITLE_FLAG],
  ['DIFF_META_KEY', DIFF_META_KEY],
  ['DIFFS_AGGREGATED_META_KEY', DIFFS_AGGREGATED_META_KEY],
  ['FIRST_REFERENCE_KEY_PROPERTY', FIRST_REFERENCE_KEY_PROPERTY],
])
