CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  login character varying(30) NOT NULL
    CONSTRAINT users_login_length CHECK (char_length(login) >= 3),
  password character(32) NOT NULL,
  email character varying(200)
    CONSTRAINT users_email_length CHECK (char_length(email) >= 6),
  enabled boolean NOT NULL DEFAULT true,
  registration_date timestamp without time zone NOT NULL,
  CONSTRAINT users_login_key UNIQUE (login)
);

COMMENT ON COLUMN public.users.login IS 'Stub column comment for ddlapi sample fixture testing.';

COMMENT ON INDEX users_login_key IS 'Stub long comment for ddlapi viewer sample fixtures and Storybook testing only. This placeholder text is intentionally verbose so the API doc viewer can render multiline column and index descriptions at realistic lengths without using production documentation. Segment A: lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Segment B: ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Segment C: duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore end stub.';
