FROM docker.io/nginx:1.31.3-alpine3.24

COPY nginx/errors                        /var/www/error
COPY nginx/nginx.conf.template           /app/nginx.conf.template
COPY nginx/entrypoint.sh                 /tmp

COPY packages/agents/dist                /usr/share/nginx/html/agents
COPY packages/portal/dist                /usr/share/nginx/html/portal

# giving permissions to nginx
RUN chmod -R 777 /var/log/nginx /var/cache/nginx/ /var/run/ /usr/share/nginx/html/ && \
    chmod -R +x /tmp/

EXPOSE 8080

USER 1000

ENTRYPOINT ["/tmp/entrypoint.sh"]
