# yamllint disable-file
---
apiVersion: v1
data:
  config.yaml: {{ .Values.qubershipApihubAgentsBackend.env | toYaml | b64enc }}
kind: Secret
metadata:
  name: qubership-apihub-agents-backend-config-secret
  labels:
      app.kubernetes.io/part-of: qubership-apihub
      app.kubernetes.io/managed-by: helm
type: Opaque