# yamllint disable-file
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: 'qubership-api-linter-service'
    labels:
        name: 'qubership-api-linter-service'
        app.kubernetes.io/name: 'qubership-api-linter-service'
        app.kubernetes.io/version: '{{ .Values.qubershipApiLinterService.version }}'
        app.kubernetes.io/component: 'backend'
        app.kubernetes.io/part-of: 'qubership-api-linter-service'
        app.kubernetes.io/managed-by: 'helm'
        app.kubernetes.io/technology: 'go'
        olric-cluster: apihub
spec:
    replicas: {{ .Values.qubershipApiLinterService.replicas }}
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
    template:
        metadata:
            labels:
                name: 'qubership-api-linter-service'
                app.kubernetes.io/name: 'qubership-api-linter-service'
                app.kubernetes.io/version: '{{ .Values.qubershipApiLinterService.version }}'
                app.kubernetes.io/component: 'backend'
                app.kubernetes.io/part-of: 'qubership-api-linter-service'
                app.kubernetes.io/managed-by: 'helm'
                app.kubernetes.io/technology: 'go'
                olric-cluster: apihub
        spec:
            hostPID: false
            hostIPC: false
            serviceAccountName: 'qubership-api-linter-service'
            volumes:
            - name: qubership-api-linter-service-config
              secret:
                defaultMode: 420
                secretName: qubership-api-linter-service-config-secret
            - name: tmp-volume
              emptyDir: {}
            {{- if and .Values.qubershipApiLinterService.customCa.enabled .Values.qubershipApiLinterService.customCa.secretName }}
            - name: qubership-api-linter-service-custom-ca
              secret:
                  defaultMode: 420
                  secretName: {{ .Values.qubershipApiLinterService.customCa.secretName | quote }}
            {{- end }}
            containers:
            - name: 'qubership-api-linter-service'
              image: '{{ .Values.qubershipApiLinterService.image.repository }}:{{ .Values.qubershipApiLinterService.image.tag }}'
              volumeMounts:
              - name: qubership-api-linter-service-config
                mountPath: /app/qubership-api-linter-service/etc/
              - name: tmp-volume
                mountPath: /tmp
              {{- if and .Values.qubershipApiLinterService.customCa.enabled .Values.qubershipApiLinterService.customCa.secretName }}
              - name: qubership-api-linter-service-custom-ca
                mountPath: /tmp/cert
                readOnly: true
              {{- end }}
              ports:
              - name: web
                containerPort: 8080
                protocol: TCP
              env:
              - name: LOG_LEVEL
                value: '{{ .Values.qubershipApiLinterService.env.logLevel }}'
              - name: GOMEMLIMIT
                value: '{{ .Values.qubershipApiLinterService.goMemLimit | default "800MiB" }}'
              - name: LINTER_CONFIG_FOLDER
                value: '/app/qubership-api-linter-service/etc/'
              resources:
                requests:
                    cpu: {{ .Values.qubershipApiLinterService.resource.cpu.request }}
                    memory: '{{ .Values.qubershipApiLinterService.resource.memory.request }}'
                limits:
                    cpu: {{ .Values.qubershipApiLinterService.resource.cpu.limit }}
                    memory: '{{ .Values.qubershipApiLinterService.resource.memory.limit }}'
              livenessProbe:
                httpGet:
                    path: /live
                    port: web
                initialDelaySeconds: 35
                timeoutSeconds: 10
              readinessProbe:
                httpGet:
                    path: /ready
                    port: web
                initialDelaySeconds: 35
                timeoutSeconds: 10
              securityContext:
                runAsUser: 10001
                runAsGroup: 10001
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                seccompProfile:
                    type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                    drop:
                        - ALL
    selector:
        matchLabels:
            name: 'qubership-api-linter-service'

