FROM docker.io/node:24-alpine

WORKDIR /usr/src/app

COPY .npmrc .npmrc
COPY package.json ./
COPY npm-shrinkwrap.json ./
RUN npm ci
COPY dist dist

USER 10001

CMD [ "node", "--max-old-space-size=3100", "--max-semi-space-size=32", "dist/main" ]
