type Query {
    salesOrder: SalesOrder
}

type SalesOrder {
    id: String
    price: Price
}

type Price {
    oneTimeDiscount: MonetaryValue
    oneTimeTotalWithTax: MonetaryValue
    oneTimeTotalWithTaxDiscounted: MonetaryValue
}

type Mutation {
    createSalesOrder(input: CreateSalesOrderInput): SalesOrder
}

input CreateSalesOrderInput {
    prices: [PriceInput]
}

input PriceInput {
    oneTimeDiscount: MonetaryValue
    oneTimeTotalWithTax: MonetaryValue
}

enum MonetaryValue {
    CNY
    RUB
}