const DDL_SCALAR_COLUMN_TYPE_NAMES = new Set([
  'bigint',
  'bigserial',
  'bit',
  'bit varying',
  'bool',
  'boolean',
  'bytea',
  'char',
  'character',
  'character varying',
  'date',
  'decimal',
  'double precision',
  'float',
  'float4',
  'float8',
  'int',
  'int2',
  'int4',
  'int8',
  'integer',
  'interval',
  'json',
  'jsonb',
  'money',
  'numeric',
  'real',
  'serial',
  'serial2',
  'serial4',
  'serial8',
  'smallint',
  'smallserial',
  'text',
  'time',
  'time with time zone',
  'time without time zone',
  'timestamp',
  'timestamp with time zone',
  'timestamp without time zone',
  'timestamptz',
  'timetz',
  'uuid',
  'varbit',
  'varchar',
])

export function isDdlScalarColumnTypeName(typeName: string): boolean {
  return DDL_SCALAR_COLUMN_TYPE_NAMES.has(typeName.trim().toLowerCase())
}
